<?php
/*
$myfile = fopen("newfile.txt", "w") or die("Unable to open file!");
$txt = "John Doe\n";
fwrite($myfile, $txt);
$txt = "Jane Doe\n";
fwrite($myfile, $txt);
fclose($myfile);
var_dump($_POST);

 */
?>
<!DOCTYPE html>
<html lang="hr">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <style>
            input, textarea { display: block; }
        </style>
    </head>
    <body>

        <header>
            <ul>
                <li><a href="/p4/mvc-app/">Naslovnica</a></li>
                <li><a href="/p4/mvc-app/form/index">Prijavi se</a></li>
                <li> Login (za admine)</li>
            </ul>
        </header>

        <main>

            <h1>Prijavnica za PHP akademiju</h1>

            <p>Prijavnica za prvo osječko izdanje PHP akademije koju Inchoo pokreće u suradnji s FERITom.</p>
            <p>Prijave traju do 10.10., pa požuri i svoje mjesto rezerviraj već sad.</p>
            <p>Više informacija na:
                <a href="http://inchoo.hr/php-akademija-2016/" target="_blank">http://inchoo.hr/php-akademija-2016/</a>
            </p>

            <!-- fix form -->
            <form action="/p4/mvc-app/form/submit" method="post">
                <label>Ime i prezime</label>
                <input type="text" name="name" />

                <label>Mail adresa</label>
                <input type="email" name="email" />

                <label>Smjer</label>
                <input type="text" name="study" />
                <br>

                <label>Godina studija</label>
                <select name="godina">
                    <option value="1">1.</option>
                    <option value="2">2.</option>
                    <option value="3">3.</option>
                </select>
                <br><br>

                <label>Što te motiviralo da se prijaviš?</label>
                <textarea type="text" name="motiv">

                </textarea>
                <br>

                <label>Imaš li predznanje vezano uz web development?</label>
                <textarea type="text" name="preknow">

                </textarea>
                <br>

                U kojim jezicima si do sada programirao?
                <label><input name="language[]" type="checkbox" value="C" />C programski jezik</label>
                <label><input name="language[]" type="checkbox" value="PHP"/>PHP</label>
                <br><br>

                Uploadaj primjer svoga koda:
                <input type="file">
                <br><br>
                <button type="submit">Submit</button>
            </form>
        </main>

        <footer>
            <p>&copy; PHP Akademija, 2016</p>
        </footer>

    </body>
</html>